//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManTechTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintsType()
        {
            this.Complaints = new HashSet<Complaint>();
        }
    
        public int ComplainTypeId { get; set; }
        public string ComplainType { get; set; }
        public Nullable<int> ComplainCategoryId { get; set; }
        public Nullable<int> PriorityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ComplaintsCategory ComplaintsCategory { get; set; }
        public virtual Priority Priority { get; set; }
    }
}
