//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManTechTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintsCategory()
        {
            this.Complaints = new HashSet<Complaint>();
            this.ComplaintsTypes = new HashSet<ComplaintsType>();
        }
    
        public int ComplainCategoryId { get; set; }
        public string ComplainCategory { get; set; }
        public Nullable<int> PriorityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintsType> ComplaintsTypes { get; set; }
    }
}
